interface track {
    title: string
    duration: number
    track_number: number
    filename: string
    id: number
}

interface album {
    id: number
    title: string
    artist: string
    path: string
    track_list: track[]
}

const albums: album[] = [
    {
        id: 1,
        title: 'Cold Water Music',
        artist: 'Aim',
        path: 'Aim/Cold Water Music',
        track_list: [
            {
                title: 'Intro',
                duration: 55,
                track_number: 1,
                filename: '01 - Intro.mp3',
                id: 1,
            },
            {
                title: 'Cold Water Music',
                duration: 344,
                track_number: 2,
                filename: '02 - Cold Water Music.mp3',
                id: 2,
            },
            {
                title: 'The Force',
                duration: 245,
                track_number: 3,
                filename: "03 - The Force (Feat Q 'n' C).mp3",
                id: 3,
            },
            {
                title: 'Sail',
                duration: 314,
                track_number: 4,
                filename: '04 - Sail (Feat Kate Rogers).mp3',
                id: 4,
            },
            {
                title: 'Downstate',
                duration: 254,
                track_number: 5,
                filename: '05 - Downstate.mp3',
                id: 5,
            },
            {
                title: 'Ain’t Got Time to Waste',
                duration: 248,
                track_number: 6,
                filename: "06 - Ain't Got Time To Waste (Feat YZ).mp3",
                id: 6,
            },
            {
                title: 'Fat City (interlude)',
                duration: 39,
                track_number: 7,
                filename: '07 - Fat City (Interlude).mp3',
                id: 7,
            },
            {
                title: 'True to Hip Hop',
                duration: 268,
                track_number: 8,
                filename: '08 - True To Hip Hop (Feat AG).mp3',
                id: 8,
            },

            {
                title: 'Demonique',
                duration: 318,
                track_number: 9,
                filename: '09 - Demonique.mp3',
                id: 9,
            },
            {
                title: 'A Tree, a Rock and a Cloud',
                duration: 257,
                track_number: 10,
                filename: '10 - A Tree, A Rock And A Cloud.mp3',
                id: 10,
            },
            {
                title: 'Journey to the End of Night',
                duration: 327,
                track_number: 11,
                filename: '11 - Journey To The End Of The Night.mp3',
                id: 11,
            },
            {
                title: 'From Here to Fame',
                duration: 329,
                track_number: 12,
                filename: '12 - From Here To Fame (Feat YZ).mp3',
                id: 12,
            },
        ],
    },
    {
        id: 2,
        title: 'Moon Safari',
        artist: 'Air',
        path: 'Air/Moon Safari',
        track_list: [
            {
                title: 'La Femme d’argent',
                duration: 431,
                track_number: 1,
                filename: "01 - La Femme d'Argent.mp3",
                id: 1,
            },
            {
                title: 'Sexy Boy',
                duration: 298,
                track_number: 2,
                filename: '02 - Sexy Boy.mp3',
                id: 2,
            },
            {
                title: 'All I Need',
                duration: 268,
                track_number: 3,
                filename: '03 - All I Need.mp3',
                id: 3,
            },
            {
                title: 'Kelly Watch the Stars',
                duration: 225,
                track_number: 4,
                filename: '04 - Kelly Watch The Stars.mp3',
                id: 4,
            },
            {
                title: 'Talisman',
                duration: 256,
                track_number: 5,
                filename: '05 - Talisman.mp3',
                id: 5,
            },
            {
                title: 'Remember',
                duration: 154,
                track_number: 6,
                filename: '06 - Remember.mp3',
                id: 6,
            },
            {
                title: 'You Make It Easy',
                duration: 241,
                track_number: 7,
                filename: '07 - You Make It Easy.mp3',
                id: 7,
            },
            {
                title: 'Ce matin là',
                duration: 219,
                track_number: 8,
                filename: '08 - Ce Matin La.mp3',
                id: 8,
            },
            {
                title: 'New Star in the Sky (Chanson pour Solal)',
                duration: 340,
                track_number: 9,
                filename: '09 - New Star In The Sky.mp3',
                id: 9,
            },
            {
                title: 'Le Voyage de Pénélope',
                duration: 190,
                track_number: 10,
                filename: '10 - Le Voyage de Penelope.mp3',
                id: 10,
            },
        ],
    },
    {
        id: 3,
        title: 'Jagged Little Pill',
        artist: 'Alanis Morissette',
        path: 'Alanis Morissette/Jagged Little Pill',
        track_list: [
            {
                title: 'All I Really Want',
                duration: 284,
                track_number: 1,
                filename: '01 - All I Really Want.mp3',
                id: 1,
            },
            {
                title: 'You Oughta Know',
                duration: 248,
                track_number: 2,
                filename: '02 - You Oughta Know.mp3',
                id: 2,
            },
            {
                title: 'Perfect',
                duration: 187,
                track_number: 3,
                filename: '03 - Perfect.mp3',
                id: 3,
            },
            {
                title: 'Hand in My Pocket',
                duration: 221,
                track_number: 4,
                filename: '04 - Hand in My Pocket.mp3',
                id: 4,
            },
            {
                title: 'Right Through You',
                duration: 175,
                track_number: 5,
                filename: '05 - Right Through You.mp3',
                id: 5,
            },
            {
                title: 'Forgiven',
                duration: 299,
                track_number: 6,
                filename: '06 - Forgiven.mp3',
                id: 6,
            },
            {
                title: 'You Learn',
                duration: 239,
                track_number: 7,
                filename: '07 - You Learn.mp3',
                id: 7,
            },
            {
                title: 'Head Over Feet',
                duration: 267,
                track_number: 8,
                filename: '08 - Head Over Feet.mp3',
                id: 8,
            },
            {
                title: 'Mary Jane',
                duration: 280,
                track_number: 9,
                filename: '09 - Mary Jane.mp3',
                id: 9,
            },
            {
                title: 'Ironic',
                duration: 229,
                track_number: 10,
                filename: '10 - Ironic.mp3',
                id: 10,
            },
            {
                title: 'Not the Doctor',
                duration: 227,
                track_number: 11,
                filename: '11 - Not the Doctor.mp3',
                id: 11,
            },
            {
                title: 'Wake Up',
                duration: 293,
                track_number: 12,
                filename: '12 - Wake Up.mp3',
                id: 12,
            },
        ],
    },
    {
        id: 4,
        title: '1977',
        artist: 'Ash',
        path: 'Ash/1977',
        track_list: [
            {
                title: 'Lose Control',
                duration: 217,
                track_number: 1,
                filename: '01 - Lose Control.mp3',
                id: 1,
            },
            {
                title: 'Goldfinger',
                duration: 271,
                track_number: 2,
                filename: '02 - Goldfinger.mp3',
                id: 2,
            },
            {
                title: 'Girl From Mars',
                duration: 210,
                track_number: 3,
                filename: '03 - Girl From Mars.mp3',
                id: 3,
            },
            {
                title: 'I’d Give You Anything',
                duration: 271,
                track_number: 4,
                filename: "04 - I'd Give You Anything.mp3",
                id: 4,
            },
            {
                title: 'Gone the Dream',
                duration: 209,
                track_number: 5,
                filename: '05 - Gone The Dream.mp3',
                id: 5,
            },
            {
                title: 'Kung Fu',
                duration: 137,
                track_number: 6,
                filename: '06 - Kung Fu.mp3',
                id: 6,
            },
            {
                title: 'Oh Yeah',
                duration: 285,
                track_number: 7,
                filename: '07 - Oh Yeah.mp3',
                id: 7,
            },
            {
                title: 'Let It Flow',
                duration: 282,
                track_number: 8,
                filename: '08 - Let It Flow.mp3',
                id: 8,
            },
            {
                title: 'Innocent Smile',
                duration: 352,
                track_number: 9,
                filename: '09 - Innocent Smile.mp3',
                id: 9,
            },
            {
                title: 'Angel Interceptor',
                duration: 244,
                track_number: 10,
                filename: '10 - Angel Interceptor.mp3',
                id: 10,
            },
            {
                title: 'Lost in You',
                duration: 259,
                track_number: 11,
                filename: '11 - Lost In You.mp3',
                id: 11,
            },
            {
                title: 'Darkside Lightside / Sick Party',
                duration: 1007,
                track_number: 12,
                filename: '12 - Darkside Lightside.mp3',
                id: 12,
            },
        ],
    },
    {
        id: 5,
        title: 'Parachutes',
        artist: 'Coldplay',
        path: 'Coldplay/Parachutes',
        track_list: [
            {
                title: "Don't Panic",
                duration: 137,
                track_number: 1,
                filename: "01. Don't Panic.mp3",
                id: 1,
            },
            {
                title: 'Shiver',
                duration: 299,
                track_number: 2,
                filename: '02. Shiver.mp3',
                id: 2,
            },
            {
                title: 'Spies',
                duration: 318,
                track_number: 3,
                filename: '03. Spies.mp3',
                id: 3,
            },
            {
                title: 'Sparks',
                duration: 227,
                track_number: 4,
                filename: '04. Sparks.mp3',
                id: 4,
            },
            {
                title: 'Yellow',
                duration: 269,
                track_number: 5,
                filename: '05. Yellow.mp3',
                id: 5,
            },
            {
                title: 'Trouble',
                duration: 270,
                track_number: 6,
                filename: '06. Trouble.mp3',
                id: 6,
            },
            {
                title: 'Parachutes',
                duration: 46,
                track_number: 7,
                filename: '07. Parachutes.mp3',
                id: 7,
            },
            {
                title: 'High Speed',
                duration: 254,
                track_number: 8,
                filename: '08. High Speed.mp3',
                id: 8,
            },
            {
                title: 'We Never Change',
                duration: 249,
                track_number: 9,
                filename: '09. We Never Change.mp3',
                id: 9,
            },
            {
                title: "Everything's Not Lost / Life Is for Living",
                duration: 435,
                track_number: 10,
                filename: "10. Everything's Not Lost.mp3",
                id: 10,
            },
        ],
    },
    {
        id: 6,
        title: 'Discovery',
        artist: 'Daft Punk',
        path: 'Daft Punk/Discovery',
        track_list: [
            {
                title: 'One More Time',
                duration: 320,
                track_number: 1,
                filename: '01 - Daft Punk - One More Time.mp3',
                id: 1,
            },
            {
                title: 'Aerodynamic',
                duration: 207,
                track_number: 2,
                filename: '02 - Daft Punk - Aerodynamic.mp3',
                id: 2,
            },
            {
                title: 'Digital Love',
                duration: 298,
                track_number: 3,
                filename: '03 - Daft Punk - Digital Love.mp3',
                id: 3,
            },
            {
                title: 'Harder, Better, Faster, Stronger',
                duration: 224,
                track_number: 4,
                filename: '04 - Daft Punk - Harder, Better, Faster, Stronger.mp3',
                id: 4,
            },
            {
                title: 'Crescendolls',
                duration: 211,
                track_number: 5,
                filename: '05 - Daft Punk - Crescendolls.mp3',
                id: 5,
            },
            {
                title: 'Nightvision',
                duration: 104,
                track_number: 6,
                filename: '06 - Daft Punk - Nightvision.mp3',
                id: 6,
            },
            {
                title: 'Superheroes',
                duration: 237,
                track_number: 7,
                filename: '07 - Daft Punk - Superheroes.mp3',
                id: 7,
            },
            {
                title: 'High Life',
                duration: 201,
                track_number: 8,
                filename: '08 - Daft Punk - High Life.mp3',
                id: 8,
            },
            {
                title: 'Something About Us',
                duration: 231,
                track_number: 9,
                filename: '09 - Daft Punk - Something About Us.mp3',
                id: 9,
            },
            {
                title: 'Voyager',
                duration: 227,
                track_number: 10,
                filename: '10 - Daft Punk - Voyager.mp3',
                id: 10,
            },
            {
                title: 'Veridis Quo',
                duration: 344,
                track_number: 11,
                filename: '11 - Daft Punk - Veridis Quo.mp3',
                id: 11,
            },
            {
                title: 'Short Circuit',
                duration: 206,
                track_number: 12,
                filename: '12 - Daft Punk - Short Circuit.mp3',
                id: 12,
            },
            {
                title: 'Face to Face',
                duration: 240,
                track_number: 13,
                filename: '13 - Daft Punk - Face To Face.mp3',
                id: 13,
            },
            {
                title: 'Too Long',
                duration: 600,
                track_number: 14,
                filename: '14 - Daft Punk - Too Long.mp3',
                id: 14,
            },
        ],
    },
    {
        id: 7,
        title: 'Hunky Dory',
        artist: 'David Bowie',
        path: 'David Bowie/Hunky Dory',
        track_list: [
            {
                title: 'Changes',
                duration: 216,
                track_number: 1,
                filename: '01.Changes.mp3',
                id: 1,
            },
            {
                title: 'Oh! You Pretty Things',
                duration: 192,
                track_number: 2,
                filename: '02.Oh! You Pretty Things.mp3',
                id: 2,
            },
            {
                title: 'Eight Line Poem',
                duration: 176,
                track_number: 3,
                filename: '03.Eight Line Poem.mp3',
                id: 3,
            },
            {
                title: 'Life on Mars?',
                duration: 233,
                track_number: 4,
                filename: '04.Life On Mars.mp3',
                id: 4,
            },
            {
                title: 'Kooks',
                duration: 173,
                track_number: 5,
                filename: '05.Kooks.mp3',
                id: 5,
            },
            {
                title: 'Quicksand',
                duration: 309,
                track_number: 6,
                filename: '06.Quicksand.mp3',
                id: 6,
            },
            {
                title: 'Fill Your Heart',
                duration: 187,
                track_number: 7,
                filename: '07.Fill Your Heart.mp3',
                id: 7,
            },
            {
                title: 'Andy Warhol',
                duration: 236,
                track_number: 8,
                filename: '08.Andy Warhol.mp3',
                id: 8,
            },
            {
                title: 'Song for Bob Dylan',
                duration: 252,
                track_number: 9,
                filename: '09.Song For Bob Dylan.mp3',
                id: 9,
            },
            {
                title: 'Queen Bitch',
                duration: 198,
                track_number: 10,
                filename: '10.Queen Bitch.mp3',
                id: 10,
            },
            {
                title: 'The Bewlay Brothers',
                duration: 327,
                track_number: 11,
                filename: '11.The Bewlay Brothers.mp3',
                id: 11,
            },
            {
                title: 'Bombers',
                duration: 161,
                track_number: 12,
                filename: '12.Bombers.mp3',
                id: 12,
            },
            {
                title: 'The Supermen (alternate version)',
                duration: 164,
                track_number: 13,
                filename: '13.The Supermen.mp3',
                id: 13,
            },
            {
                title: 'Quicksand (demo version)',
                duration: 286,
                track_number: 14,
                filename: '14.Quicksand (2).mp3',
                id: 14,
            },
            {
                title: 'The Bewlay Brothers (alternate mix)',
                duration: 321,
                track_number: 15,
                filename: '15.The Bewlay Brothers (2).mp3',
                id: 15,
            },
        ],
    },
    {
        id: 8,
        title: 'Elastica',
        artist: 'Elastica',
        path: 'Elastica/Elastica',
        track_list: [
            {
                title: 'Line Up',
                duration: 195,
                track_number: 1,
                filename: '01. Elastica - Line Up.mp3',
                id: 1,
            },
            {
                title: 'Annie',
                duration: 73,
                track_number: 2,
                filename: '02. Elastica - Annie.mp3',
                id: 2,
            },
            {
                title: 'Connection',
                duration: 140,
                track_number: 3,
                filename: '03. Elastica - Connection.mp3',
                id: 3,
            },
            {
                title: 'Car Song',
                duration: 144,
                track_number: 4,
                filename: '04. Elastica - Car Song.mp3',
                id: 4,
            },
            {
                title: 'Smile',
                duration: 100,
                track_number: 5,
                filename: '05. Elastica - Smile.mp3',
                id: 5,
            },
            {
                title: 'Hold Me Now',
                duration: 152,
                track_number: 6,
                filename: '06. Elastica - Hold Me Now.mp3',
                id: 6,
            },
            {
                title: 'S.O.F.T.',
                duration: 238,
                track_number: 7,
                filename: '07. Elastica - S.O.F.T..mp3',
                id: 7,
            },
            {
                title: 'Indian Song',
                duration: 166,
                track_number: 8,
                filename: '08. Elastica - Indian Song.mp3',
                id: 8,
            },
            {
                title: 'Blue',
                duration: 141,
                track_number: 9,
                filename: '09. Elastica - Blue.mp3',
                id: 9,
            },
            {
                title: 'All-Nighter',
                duration: 93,
                track_number: 10,
                filename: '10. Elastica - All-Nighter.mp3',
                id: 10,
            },
            {
                title: 'Waking Up',
                duration: 195,
                track_number: 11,
                filename: '11. Elastica - Waking Up.mp3',
                id: 11,
            },
            {
                title: '2:1',
                duration: 151,
                track_number: 12,
                filename: '12. Elastica - 2-1.mp3',
                id: 12,
            },
            {
                title: 'See That Animal',
                duration: 141,
                track_number: 13,
                filename: '13. Elastica - See That Animal.mp3',
                id: 13,
            },
            {
                title: 'Stutter',
                duration: 142,
                track_number: 14,
                filename: '14. Elastica - Stutter.mp3',
                id: 14,
            },
            {
                title: 'Never Here',
                duration: 266,
                track_number: 15,
                filename: '15. Elastica - Never Here.mp3',
                id: 15,
            },
            {
                title: 'Vaseline',
                duration: 84,
                track_number: 16,
                filename: '16. Elastica - Vaseline.mp3',
                id: 16,
            },
        ],
    },
    {
        id: 9,
        title: 'Franz Ferdinand',
        artist: 'Franz Ferdinand',
        path: 'Franz Ferdinand/Franz Ferdinand',
        track_list: [
            {
                title: 'Jacqueline',
                duration: 229,
                track_number: 1,
                filename: '01 - Jacqueline.mp3',
                id: 1,
            },
            {
                title: 'Tell Her Tonight',
                duration: 137,
                track_number: 2,
                filename: '02 - Tell Her Tonight.mp3',
                id: 2,
            },
            {
                title: 'Take Me Out',
                duration: 237,
                track_number: 3,
                filename: '03 - Take Me Out.mp3',
                id: 3,
            },
            {
                title: 'The Dark of the Matinée',
                duration: 243,
                track_number: 4,
                filename: '04 - The Dark Of The Matinee.mp3',
                id: 4,
            },
            {
                title: 'Auf Achse',
                duration: 259,
                track_number: 5,
                filename: '05 - Auf Achse.mp3',
                id: 5,
            },
            {
                title: 'Cheating on You',
                duration: 156,
                track_number: 6,
                filename: '06 - Cheating On You.mp3',
                id: 6,
            },
            {
                title: 'This Fire',
                duration: 254,
                track_number: 7,
                filename: '07 - This Fire.mp3',
                id: 7,
            },
            {
                title: 'Michael',
                duration: 201,
                track_number: 9,
                filename: '09 - Michael.mp3',
                id: 9,
            },
            {
                title: 'Come On Home',
                duration: 226,
                track_number: 10,
                filename: '10 - Come On Home.mp3',
                id: 10,
            },
            { title: '40′', duration: 204, track_number: 11, filename: "11 - 40'.mp3", id: 11 },
        ],
    },
    {
        id: 10,
        title: 'Details',
        artist: 'Frou Frou',
        path: 'Frou Frou/Details',
        track_list: [
            {
                title: 'Let Go',
                duration: 253,
                track_number: 1,
                filename: 'Frou Frou - 01 - Let Go.mp3',
                id: 1,
            },
            {
                title: 'Breathe In',
                duration: 277,
                track_number: 2,
                filename: 'Frou Frou - 02 - Breathe In.mp3',
                id: 2,
            },
            {
                title: 'It’s Good to Be in Love',
                duration: 279,
                track_number: 3,
                filename: "Frou Frou - 03 - It's Good To Be In Love.mp3",
                id: 3,
            },
            {
                title: 'Must Be Dreaming',
                duration: 242,
                track_number: 4,
                filename: 'Frou Frou - 04 - Must Be Dreaming.mp3',
                id: 4,
            },
            {
                title: 'Psychobabble',
                duration: 333,
                track_number: 5,
                filename: 'Frou Frou - 05 - Psychobabble.mp3',
                id: 5,
            },
            {
                title: 'Only Got One',
                duration: 249,
                track_number: 6,
                filename: 'Frou Frou - 06 - Only Got One.mp3',
                id: 6,
            },
            {
                title: 'Shh',
                duration: 334,
                track_number: 7,
                filename: 'Frou Frou - 07 - Shh.mp3',
                id: 7,
            },
            {
                title: 'Hear Me Out',
                duration: 259,
                track_number: 8,
                filename: 'Frou Frou - 08 - Hear Me Out.mp3',
                id: 8,
            },
            {
                title: 'Maddening Shroud',
                duration: 217,
                track_number: 9,
                filename: 'Frou Frou - 09 - Maddening Shroud.mp3',
                id: 9,
            },
            {
                title: 'Flicks',
                duration: 238,
                track_number: 10,
                filename: 'Frou Frou - 10 - Flicks.mp3',
                id: 10,
            },
            {
                title: 'The Dumbing Down of Love',
                duration: 284,
                track_number: 11,
                filename: 'Frou Frou - 11 - The Dumbing Down Of Love.mp3',
                id: 11,
            },
        ],
    },
    {
        id: 11,
        title: 'Garbage',
        artist: 'Garbage',
        path: 'Garbage/Garbage',
        track_list: [
            {
                title: 'Supervixen',
                duration: 235,
                track_number: 1,
                filename: '01 - Garbage - Supervixen.mp3',
                id: 1,
            },
            {
                title: 'Queer',
                duration: 276,
                track_number: 2,
                filename: '02 - Garbage - Queer.mp3',
                id: 2,
            },
            {
                title: 'Only Happy When It Rains',
                duration: 236,
                track_number: 3,
                filename: '03 - Garbage - Only Happy When It Rains.mp3',
                id: 3,
            },
            {
                title: 'As Heaven Is Wide',
                duration: 283,
                track_number: 4,
                filename: '04 - Garbage - As Heaven Is Wide.mp3',
                id: 4,
            },
            {
                title: 'Not My Idea',
                duration: 228,
                track_number: 5,
                filename: '05 - Garbage - Not My Idea.mp3',
                id: 5,
            },
            {
                title: 'A Stroke of Luck',
                duration: 284,
                track_number: 6,
                filename: '06 - Garbage - A Stroke Of Luck.mp3',
                id: 6,
            },
            {
                title: 'Vow',
                duration: 269,
                track_number: 7,
                filename: '07 - Garbage - Vow.mp3',
                id: 7,
            },
            {
                title: 'Stupid Girl',
                duration: 258,
                track_number: 8,
                filename: '08 - Garbage - Stupid Girl.mp3',
                id: 8,
            },
            {
                title: 'Dog New Tricks',
                duration: 237,
                track_number: 9,
                filename: '09 - Garbage - Dog New Tricks.mp3',
                id: 9,
            },
            {
                title: 'My Lover’s Box',
                duration: 234,
                track_number: 10,
                filename: "10 - Garbage - My Lover's Box.mp3",
                id: 10,
            },
            {
                title: 'Fix Me Now',
                duration: 283,
                track_number: 11,
                filename: '11 - Garbage - Fix Me Now.mp3',
                id: 11,
            },
            {
                title: 'Milk',
                duration: 235,
                track_number: 12,
                filename: '12 - Garbage - Milk.mp3',
                id: 12,
            },
        ],
    },
    {
        id: 12,
        title: 'Hope Is Important',
        artist: 'Idlewild',
        path: 'Idlewild/Hope Is important',
        track_list: [
            {
                title: "You've Lost Your Way",
                duration: 90,
                track_number: 1,
                filename: "You've Lost Your Way.mp3",
                id: 1,
            },
            {
                title: 'A Film for the Future',
                duration: 205,
                track_number: 2,
                filename: 'A Film For The Future.mp3',
                id: 2,
            },
            {
                title: 'Paint Nothing',
                duration: 191,
                track_number: 3,
                filename: 'Paint Nothing.mp3',
                id: 3,
            },
            {
                title: 'When I Argue I See Shapes',
                duration: 264,
                track_number: 4,
                filename: 'When I Argue I See Shapes.mp3',
                id: 4,
            },
            {
                title: '4 People Do Good',
                duration: 118,
                track_number: 5,
                filename: '4 People Do Good.mp3',
                id: 5,
            },
            {
                title: "I'm Happy to Be Here Tonight",
                duration: 190,
                track_number: 6,
                filename: "I'm Happy To Be Here Tonight.mp3",
                id: 6,
            },
            {
                title: "Everyone Says You're So Fragile",
                duration: 137,
                track_number: 7,
                filename: "Everyone Says You're So Fragile.mp3",
                id: 7,
            },
            {
                title: "I'm a Message",
                duration: 148,
                track_number: 8,
                filename: "I'm A Message.mp3",
                id: 8,
            },
            {
                title: "You Don't Have the Heart",
                duration: 126,
                track_number: 9,
                filename: "You Don't Have The Heart.mp3",
                id: 9,
            },
            {
                title: 'Close the Door',
                duration: 140,
                track_number: 10,
                filename: 'Close The Door.mp3',
                id: 10,
            },
            {
                title: 'Safe and Sound',
                duration: 194,
                track_number: 11,
                filename: 'Safe And Sound.mp3',
                id: 11,
            },
            {
                title: 'Low Light',
                duration: 332,
                track_number: 12,
                filename: 'Low Light.mp3',
                id: 12,
            },
        ],
    },
]
